# Generated by Django 3.1 on 2022-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='artiles',
            name='pikcha',
            field=models.ImageField(default=2, upload_to='news/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
