# Generated by Django 3.1 on 2022-01-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220120_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='pikcha',
        ),
    ]
