# Generated by Django 3.1 on 2022-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_artiles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='img',
            field=models.ImageField(height_field=100, upload_to='media/news', verbose_name='Картинка', width_field=100),
        ),
    ]
