# Generated by Django 3.1 on 2022-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220121_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='img',
            field=models.ImageField(upload_to='news/media', verbose_name='Картинка'),
        ),
    ]
