# Generated by Django 3.1 on 2022-01-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220121_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='date',
        ),
    ]
