# Generated by Django 3.1 on 2022-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_artiles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='img',
            field=models.ImageField(upload_to='news/media/news/', verbose_name='Картинка'),
        ),
    ]
