# Generated by Django 3.1 on 2022-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220121_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='img',
            field=models.ImageField(upload_to='news/', verbose_name='Картинка'),
        ),
    ]
